### PR TITLE
backend: Remove OPL

### PR DESCRIPTION
**Pull request by matevz**
This PR:
- removes OPL chunks from the backend
- still keeps DAOv1 and BallotBox as separate contracts
- adds backend tests for creating proposal, casting vote and closing a proposal
- fixes frontend to use the new non-OPL version

### CODE REVIEW

**Comment by CedarMist** [comment]
I get the following error with metamask when creating polls - deployed against Sapphire 0.5.2 (sapphire-dev):

when I don't click quickly enough through metamask:

```
error={"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":-32000,"message":"invalid signed simulate call query: base block not found"}
```

and, when I try to click Sign quickly in metamask.

```
:{"code":-32000,"message":"core: invalid call format: Tag verification failed"},
```

-------------

Have tested on testnet & it works fine though.

------------

```diff
diff --git a/backend/contracts/DAOv1.sol b/backend/contracts/DAOv1.sol
index ab6e85b..7edb9ab 100644
--- a/backend/contracts/DAOv1.sol
+++ b/backend/contracts/DAOv1.sol
@@ -29,7 +29,7 @@ contract DAOV1 {
     mapping(ProposalId => Proposal) public proposals;
     EnumerableSet.Bytes32Set private activeProposals;
     ProposalId[] private pastProposals;
-    BallotBoxV1 private ballotBox;
+    BallotBoxV1 public immutable ballotBox;
 
     constructor() {
         ballotBox = new BallotBoxV1();
diff --git a/backend/hardhat.config.ts b/backend/hardhat.config.ts
index c3a12fa..8044d2a 100644
--- a/backend/hardhat.config.ts
+++ b/backend/hardhat.config.ts
@@ -37,46 +37,29 @@ task(TASK_EXPORT_ABIS, async (_args, hre) => {
   );
 });
 
-task('deploy-ballot-box')
-  .addParam('hostNetwork')
+task('deploy')
   .setAction(async (args, hre) => {
     await hre.run('compile');
-    const ethers = hre.ethers;
-    const BallotBoxV1 = await ethers.getContractFactory('BallotBoxV1');
-    const signer = ethers.provider.getSigner();
-    const signerAddr = await signer.getAddress();
+    const DAOV1 = await hre.ethers.getContractFactory('DAOV1');
+    const dao = await DAOV1.deploy();
+    const receipt = await dao.deployed();
+    console.log(`VITE_DAO_V1_ADDR=${dao.address}`);
 
-    // Start by predicting the address of the DAO contract.
-    const hostConfig = hre.config.networks[args.hostNetwork];
-    if (!('url' in hostConfig)) throw new Error(`${args.hostNetwork} not configured`);
-    const provider = new ethers.providers.JsonRpcProvider(hostConfig.url);
-    let nonce = await provider.getTransactionCount(signerAddr);
-    if (args.hostNetwork === 'local') nonce++;
-    const daoAddr = ethers.utils.getContractAddress({ from: signerAddr, nonce });
-
-    const ballotBox = await BallotBoxV1.deploy(daoAddr);
-    await ballotBox.deployed();
-    console.log('expected DAO', daoAddr);
-    console.log('BallotBox', ballotBox.address);
-    return ballotBox.address;
-  });
-
-task('deploy-dao')
-  .addParam('ballotBoxAddr')
-  .setAction(async (args, hre) => {
-    await hre.run('compile');
-    const DAOv1 = await hre.ethers.getContractFactory('DAOv1');
-    const dao = await DAOv1.deploy(args.ballotBoxAddr);
-    await dao.deployed();
-    console.log('DAO', dao.address);
+    while( true ) {
+      try{
+        const bba = await dao.ballotBox();
+        console.log(`VITE_BALLOT_BOX_V1_ADDR=${bba}`);
+      }
+      catch( e ) {
+        await new Promise(r => setTimeout(r, 2000));
+        console.log('.');
+        continue;
+      }
+      break;
+    }
     return dao;
   });
 
-task('deploy-local').setAction(async (_args, hre) => {
-  await hre.run('compile');
-  const ballotBox = await hre.run('deploy-ballot-box', { hostNetwork: 'local' });
-  await hre.run('deploy-dao', { ballotBoxAddr: ballotBox });
-});
 
 const accounts = process.env.PRIVATE_KEY ? [process.env.PRIVATE_KEY] : [];
 
@@ -106,8 +89,25 @@ const config: HardhatUserConfig = {
     'sapphire_testnet': {
       url: 'https://testnet.sapphire.oasis.dev',
       chainId: 0x5aff,
-      accounts,
+      accounts: {
+        mnemonic: "test test test test test test test test test test test junk",
+        path: "m/44'/60'/0'/0",
+        initialIndex: 0,
+        count: 20,
+        passphrase: "",
+      },

```

**Review by CedarMist — COMMENTED** [review]
See comment about sapphire-dev vs testnet, and minor patch i needed to get it working (constructor args)

**Comment by matevz** [comment]
> See comment about sapphire-dev vs testnet, and minor patch i needed to get it working (constructor args)

Huh, you're fast, this is still draft ;) Will apply the fixes. I'm currently writing a test for this.

**Comment by CedarMist** [comment]
I'm getting a lot of unrecognized selector errors against both BallotBoxV1.sol and DAOv1.sol.

I have tested, I can create a poll, vote on a poll, and can close the poll, but the UI doesn't realize the poll is closed.

When creating a poll I get many unrecognized selector errors on DAOv1.sol. (just `eth_call`).

**Review by CedarMist — APPROVED** [review]
I have tested all the functionality and it works and CI is setup.

There are some non-breaking errors with unrecognized selectors. But can fix those easily in future.

**Pull request merged**
